### ISSUE TITLE
"modems": true 

### ISSUE THREAD

**Issue by Ladelltwitch** [715209/liveu_stats_bot#2]
config.json->   "modems": true

Liveu: monitoring modems
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RequestFailed(reqwest::Error { kind: Decode, source: Error("invalid type: null, expected a string", line: 1, column: 173) })', D:\a\liveu_stats_bot\liveu_stats_bot\src\liveu_monitor.rs:30:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by 715209** [comment]
Hello Ladell,

There seems to be a field that's optional, unfortunately this error doesn't tell me which field that is.
